export {
	definePreset,
	fallbackPreset,
	getPreset,
	mergePreset,
	mergePresetLayers,
	setPreset,
	type BuiltInPresetModuleMap,
	type FallbackPreset,
	type MergedPresetLayers,
	type Motion,
	type MotionAnimateFunction,
	type MotionCleanup,
	type MotionInitialFunction,
	type MotionTransitionFunction,
	type Preset,
	type PresetContext,
	type PresetEntry,
	type PresetEntryRecord,
	type PresetEntryValue,
	type PresetKey,
	type PresetLike,
	type PresetModuleMap,
	type PresetModuleName,
	type PresetRender,
	type ResolvedMotion
} from './preset.svelte';
export { BUILT_IN_PRESET_KEYS, type BuiltInPresetName } from '$ixirjs/ui/preset/manifest';
