/**
 * Own-cost ledger: a CPU profile of one mount attributed to the INNERMOST component frame (a
 * component's own synchronous init, children excluded) and, inside it, to the library frames.
 * This is what found Card.Root at 28 µs against shadcn's 6 (perf-vs-shadcn-2026-08.md §17).
 *
 *   node scripts/bench-vs-own.mjs <family> <side=ixir> <n=2000> [--hydrate]
 *
 * Requires the client bundle (run bench:vs-shadcn:client once).
 */
/* eslint-disable no-undef */
import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { join } from 'node:path';
const ROOT = join(import.meta.dirname, '..');
const [family, side = 'ixir', nArg = '2000'] = process.argv
	.slice(2)
	.filter((a) => !a.startsWith('--'));
const n = Number(nArg);
const HYD = process.argv.includes('--hydrate');
const bundle = readFileSync(`${ROOT}/.bench-out/vs-client/vs-client.js`, 'utf8');
const lines = bundle.split('\n');
const LIB_START =
	lines.findIndex((l) => l.includes('node-registry.svelte.ts generated by Svelte')) + 1;
const COMP_START = lines.findIndex((l) => /^\tfunction Card_root\(/.test(l)) + 1;
const SHADCN_START = lines.findIndex((l) => /^\tfunction Shadcn_card_test\(/.test(l)) + 1;
const OURS =
	/^(Wb_[a-z_]+|Card|Tree|Data_grid|Datagrid|Accordion|Accordion_item|Alert|Root|Dropdown|Menu|Button|List|Badge|Kernel|Html_element|Rich_part|Snippet_adapter)[A-Za-z_$0-9]*$/;
function layer(fr) {
	const ln = fr.lineNumber + 1,
		nm = fr.functionName || '';
	if (fr.lineNumber < 0)
		return nm === '(garbage collector)'
			? 'gc'
			: nm === '(program)' || nm === '(idle)'
				? 'program'
				: 'native';
	if (/_test$/.test(nm)) return 'fixture';
	if (ln < LIB_START) return 'svelte';
	if (ln < COMP_START) return 'lib';
	if (OURS.test(nm)) return 'component';
	if (ln >= SHADCN_START && /^[A-Z]/.test(nm) && !OURS.test(nm)) return 'shadcn';
	return ln >= SHADCN_START ? 'shadcn/other' : 'lib';
}
let ssr;
if (HYD) {
	const { render } = await import('svelte/server');
	const { FAMILIES } = await import(pathToFileURL(`${ROOT}/.bench-out/vs-ssr/ssr-entry.js`).href);
	ssr = render(FAMILIES.find((f) => f.name === family)[side], { props: { n } }).body;
}
const browser = await chromium.launch({ args: ['--js-flags=--expose-gc'] });
const page = await browser.newPage();
await page.goto('about:blank');
await page.addScriptTag({ content: bundle });
const MOUNT = async ({ family, side, count, html }) => {
	const { mount, hydrate, unmount, flushSync } = globalThis.VsBench.svelte;
	if (globalThis.gc) {
		for (let i = 0; i < 2; i++) {
			globalThis.gc();
			await new Promise((r) => setTimeout(r, 0));
		}
	}
	const c = globalThis.VsBench.FAMILIES.find((f) => f.name === family)[side];
	const t = document.createElement('div');
	document.body.appendChild(t);
	if (html) t.innerHTML = html;
	const s = performance.now();
	const app = html
		? hydrate(c, { target: t, props: { n: count, tint: '', bump: '' } })
		: mount(c, { target: t, props: { n: count, tint: '', bump: '' }, intro: false });
	flushSync();
	const ms = performance.now() - s;
	unmount(app);
	t.remove();
	return ms;
};
const cdp = await page.context().newCDPSession(page);
await cdp.send('Profiler.enable');
await cdp.send('Profiler.setSamplingInterval', { interval: 100 });
for (let i = 0; i < 3; i++) await page.evaluate(MOUNT, { family, side, count: n, html: ssr });
await cdp.send('Profiler.start');
const ms = await page.evaluate(MOUNT, { family, side, count: n, html: ssr });
const { profile } = await cdp.send('Profiler.stop');
await browser.close();
const byId = new Map(profile.nodes.map((nd) => [nd.id, nd]));
const parent = new Map();
for (const nd of profile.nodes) for (const c of nd.children ?? []) parent.set(c, nd.id);
const total = profile.samples.length;
const self = {},
	incl = {},
	entry = {},
	selfFn = {};
const own = {},
	ownLib = {};
for (const s of profile.samples) {
	const leaf = byId.get(s);
	const lf = leaf.callFrame;
	const L = layer(lf);
	self[L] = (self[L] ?? 0) + 1;
	if (L === 'lib' || L === 'svelte') {
		const k = `${L}:${lf.functionName || '(anon)'}:${lf.lineNumber + 1}`;
		selfFn[k] = (selfFn[k] ?? 0) + 1;
	}
	const seen = new Set();
	let outermost = null;
	let id = s;
	while (id !== undefined) {
		const nd = byId.get(id);
		const fr = nd.callFrame;
		const l = layer(fr);
		if (l === 'lib' || l === 'component') {
			const k = `${fr.functionName || '(anon)'}:${fr.lineNumber + 1}`;
			if (!seen.has(k)) {
				seen.add(k);
				incl[k] = (incl[k] ?? 0) + 1;
			}
			if (l === 'lib') outermost = k;
		}
		id = parent.get(id);
	}
	const e = outermost ?? `(no lib frame: ${L})`;
	entry[e] = (entry[e] ?? 0) + 1;
	// innermost component frame → 'own' cost of that component's synchronous init (children excluded)
	let id2 = s,
		inner = null,
		libSeen = new Set(),
		libBelow = [];
	while (id2 !== undefined) {
		const fr = byId.get(id2).callFrame;
		const l = layer(fr);
		const k = `${fr.functionName || '(anon)'}:${fr.lineNumber + 1}`;
		if (l === 'component' && inner === null) inner = k;
		if (inner === null && l === 'lib' && !libSeen.has(k)) {
			libSeen.add(k);
			libBelow.push(k);
		}
		id2 = parent.get(id2);
	}
	const ik = inner ?? `(none: ${L})`;
	own[ik] = (own[ik] ?? 0) + 1;
	if (inner) {
		ownLib[ik] ??= {};
		for (const k of libBelow) ownLib[ik][k] = (ownLib[ik][k] ?? 0) + 1;
		ownLib[ik]['<self:' + L + '>'] = (ownLib[ik]['<self:' + L + '>'] ?? 0) + 1;
	}
}
const pct = (c) => ((c / total) * 100).toFixed(1).padStart(5) + '%';
console.log(
	`\n${family}/${side} n=${n} ${HYD ? 'hydrate' : 'mount'} — ${total} samples, ${ms.toFixed(0)} ms, ${((ms * 1000) / n).toFixed(1)} µs/unit`
);
console.log('\nSELF by layer:');
for (const [k, v] of Object.entries(self).sort((a, b) => b[1] - a[1]))
	console.log(`  ${pct(v)}  ${k}`);
console.log('\nINCLUSIVE by OUTERMOST lib entry point (a sample counts once):');
for (const [k, v] of Object.entries(entry)
	.sort((a, b) => b[1] - a[1])
	.slice(0, 18))
	console.log(`  ${pct(v)}  ${k}`);
console.log('\nINCLUSIVE by lib/component function (any depth):');
for (const [k, v] of Object.entries(incl)
	.sort((a, b) => b[1] - a[1])
	.slice(0, 30))
	console.log(`  ${pct(v)}  ${k}`);
console.log('\nOWN by innermost component (children excluded), µs/unit:');
for (const [k, v] of Object.entries(own)
	.sort((a, b) => b[1] - a[1])
	.slice(0, 12))
	console.log(`  ${pct(v)}  ${(((v / total) * ms * 1000) / n).toFixed(1).padStart(6)} µs  ${k}`);
for (const [ck, m] of Object.entries(ownLib)
	.sort((a, b) => own[b[0]] - own[a[0]])
	.slice(0, 4)) {
	console.log(`\n  inside ${ck} — lib frames (inclusive within that component's own samples):`);
	for (const [k, v] of Object.entries(m)
		.sort((a, b) => b[1] - a[1])
		.slice(0, 22))
		console.log(
			`    ${pct(v)}  ${(((v / total) * ms * 1000) / n).toFixed(1).padStart(6)} µs  ${k}`
		);
}
console.log('\nSELF top functions (lib + svelte):');
for (const [k, v] of Object.entries(selfFn)
	.sort((a, b) => b[1] - a[1])
	.slice(0, 25))
	console.log(`  ${pct(v)}  ${k}`);
